### ISSUE TITLE
Directory should be superadmin

### ISSUE THREAD

**Issue by francisfandino** [openfga/sample-stores#26]
https://github.com/openfga/sample-stores/blob/18f1772e720c364fc0876bfe940b22a2e2f2e764/stores/superadmin/README.md?plain=1#L26

**Comment by tmsagarofficial** [comment]
I would love to work on this issue . Pls assign it to me

**Comment by aaguiarz** [comment]
@tmsagarofficial I apologize, this was fixed as part of https://github.com/openfga/sample-stores/commit/3db31f5e8fd276560a736aff240b23916577a6da
